/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

module.exports = {
  someSidebar: [
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    {
      "Get Started": [
        "index", 
        "getting_started", 
        {
          type: "category",
          label: "Onboarding",
          collapsible: true,
          collapsed: false,
          items: [
            "team_accountability",
            "executive_reporting",
            "hidden_costs",
          ],
        },
        "vantage_account"
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: false,
      label: "Integrations",
      items: [
        {
          type: "category",
          label: "AWS",
          items: [
            "connecting_aws",
            "permissions_aws",
            "syncing",
            "supported_services",
            "security",
          ],
        },
        "connecting_azure",
        {
          type: "category",
          label: "Google Cloud",
          items: [
            "connecting_gcp",
            "permissions_gcp",
            "enabling_gcp_billing_export",
          ],
        },
        {
          type: "category",
          label: "Kubernetes",
          items: [
            "connecting_kubernetes",
            "opencost",
            "kubernetes_container_insights",
          ],
        },
        "connecting_datadog",
        "connecting_new_relic",
        "connecting_mongodb-atlas",
        {
          type: "category",
          label: "Snowflake",
          items: ["connecting_snowflake", "snowflake_cost_by_query"],
        },
        "connecting_databricks",
        "connecting_fastly",
      ],
    },
    {
      type: "category",
      collapsible: true,
      collapsed: false,
      label: "Features",
      items: [
        "overview",
        {
          type: "category",
          label: "Cost Reporting",
          items: [
            "cost_reports",
            "forecasting",
            "segments",
            "per_unit_costs",
            "cost_anomaly_alerts",
            "budgets",
          ],
        },
        {
          type: "category",
          label: "Optimization",
          items: [
            "autopilot",
            "savings_planner",
            "active_resources",
            "metrics",
          ],
        },
        {
          type: "category",
          label: "Notifications",
          items: [
            "reports",
            "slack_integration",
            "microsoft_teams_integration",
            "terraform_cloud_integration",
          ],
        },
        "workspaces",
      ],
    },
  ],
};
